<a href="https://colab.research.google.com/github/MMRES-PyBootcamp/MMRES-python-bootcamp2022/blob/main/solved_notebooks/09_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Session 9 - NumPy

## Introduction

After getting used to how Python works, it is the moment to begin getting our hands dirty with data analysis. We will study two packages: [NumPy](http://www.numpy.org/) and [Pandas](http://pandas.pydata.org/). NumPy is the fundamental numeric computing and linear algebra package in Python. We will learn it not only for the data analysis, but more importantly, because it will be a package that will be always present in our `import` section as scientists. In the next notebook, we will dive into Pandas. Pandas is a dedicated data analysis package with more functionalities than NumPy, making our life much easier in terms of data visualization and manipulation. 

Let us start importing the necessary packages.

In [1]:
import numpy as np
print('NumPy:', np.__version__)

NumPy: 1.21.6


## Numeric Python (NumPy)

NumPy is an open-source add-on module to Python that provides common mathematical and numerical routines in pre-compiled, fast functions. These are growing into highly mature packages that provide functionalities that meets that
associated with common commercial software like [MATLAB](https://www.mathworks.com/). The [NumPy](http://www.numpy.org/) (Numeric Python) package provides basic routines for manipulating large arrays and matrices of numerical data. With NumPy we will be working with *homogeneous multidimensional array* or, simply, **NumPy arrays**.

We will now explore some capabilities of NumPy that will prove very useful not only for data analyisis, but for almost any Python application.

### Creating Arrays

As mentioned before, the main object in NumPy is the *array*. Creating one is as easy as calling the command `array`

In [2]:
# Create a list
mylist = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# Create a numpy array from a list
my1darr = np.array(mylist)

# Data type of a numpy array
print(type(my1darr))

my1darr

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

The same applies to multidimensional arrays

In [3]:
# Create a numpy array with three elemets, with three elements each.
my2darr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
my2darr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# Create a numpy array with three elemets, with three elements each, with a single element each
my3darr = np.array([  [[1], [2], [3]], [[4], [5], [6]], [[7], [8], [9]]  ])
my3darr

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

A NumPy array has a number of dimensions (or *axes*). To obtain the number of axes and the size of each of them you use the command `shape`. For 2-dimensional arrays (matrices), the order corresponds to (rows, columns)

There are two different ways of calling the `shape` command, either with `np.shape(arr)` or `arr.shape`. This is not the only command that works in both formats, and we will be finding some more in our way.

In [5]:
# Shape using `.shape`
print(my1darr.shape)
print(my2darr.shape)
print(my3darr.shape)

# Shape using `np.shape()`
print(np.shape(my1darr))
print(np.shape(my2darr))
print(np.shape(my3darr))

(9,)
(3, 3)
(3, 3, 1)
(9,)
(3, 3)
(3, 3, 1)


There is one restriction with respect to the use of lists: while we can make lists containing any kind of data, all the data in a numpy array must be of the same type, and it is converted automatically.

In [6]:
# Create a list with floats and strings
lst = [1., 'cat']
print(lst)

# Create a numpy array from a list with mixed data types
arr = np.array(lst)
print(arr)

# The data type of the 1. in the list is the same data type than the 1. in the array?
print(f"Type list = type array? {((lst[0])) == type((arr[0]))}")
print(f"Type list: {type(lst[0])}")
print(f"Type array: {type(arr[0])}")

[1.0, 'cat']
['1.0' 'cat']
Type list = type array? False
Type list: <class 'float'>
Type array: <class 'numpy.str_'>


### Special Arrays

There are some functionalities that allow us to create arrays filled with determined values. `ones` and `zeros` provide arrays of the given shape and type (default is float64), filled with ones or zeros, respectively.

In [7]:
# Create a zero-filled numpy array of shape 3 x 2
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
# Create a one-filled numpy array of shape 3 x 2 x 4
np.ones((3, 2, 4), dtype=np.int8)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int8)

`eye(d)` returns a 2-D array, of size $d$ with ones in the diagonal and zeros elsewhere. It's an identity matrix.

In [9]:
# Create an numpy array of shape 3 x 3 with ones in the diagonal
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

`eye` can also make arrays with ones in upper and lower diagonals. To achieve this, you must call `eye(d, d, k)` where $k$ denotes the diagonal (positive for above the center diagonal, negative for below), or `eye(d, k=num)`

In [10]:
# Create an numpy array of shape 5 x 5 with ones in the diagonal shifted-up 2 positions
print(np.eye(5, 5, 2))
print('\n')

# Create an numpy array of shape 4 x 4 with ones in the diagonal shifted-down 1 position
print(np.eye(4, k=-1))

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


`diag`, depending on the input, either constructs a diagonal array (if the input is a 1-D array) or extracts a diagonal from a matrix (if the input is a 2-D array).

In [11]:
# Create a 2-D array with the array `my1darr` shifted-up 1 position with respect the diagonal 
np.diag(my1darr, 1)

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [12]:
# The the diagonal from the 2-D array `my2darr`
np.diag(my2darr)

array([1, 5, 9])

In [13]:
# Create a 2-D array with the diagonal from the 2-D array `my2darr` shifted-down 1 position with respect the diagonal 
np.diag(np.diag(my2darr), -1)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 9, 0]])

`arange(begin, end, step)` returns evenly spaced values within a given interval. Note that the beginning point is included, but not the ending.

In [14]:
# Create range with start at 0, stop before 16
myrange = np.arange(0, 16)
myrange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

**Exercise 1**: Create an array of the first million of odd numbers, both with `arange` and using loops. Try timing both methods to see which one is faster. Use the magic command `%timeit`

In [15]:
%timeit np.arange(0, 2000000, 2)

%timeit [i for i in range(2000000) if i % 2 == 0]

697 µs ± 63.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
337 ms ± 57.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Similarly, `linspace(begin, end, points)` returns evenly spaced numbers over a specified interval. Here, instead of specifying the step, we provide the amount of points that we need. Beware that `linspace` includes the end of the interval!

In [16]:
# Create line with start at 0, stop at 14, with 8 evenly spaced points
myline = np.linspace(0, 14, 8) # 
myline

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

`reshape` changes the shape of an array, but not its data. This is another of the commands that can be called before or after the array.

In [17]:
# Reshape `myrange` using `np.reshape()`
print(np.reshape(myline, (2, 4)))

print('\n')

# Reshape `myrange` using `.reshape()`
print(myline.reshape(4, 2))

[[ 0.  2.  4.  6.]
 [ 8. 10. 12. 14.]]


[[ 0.  2.]
 [ 4.  6.]
 [ 8. 10.]
 [12. 14.]]


Note that, however, this only provides a copy of the array. In order for them to be permanent we need to reasign the variable value.

In [18]:
# After the reshapings above, the original array stays being the same
myline  

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [19]:
new_line = myline.reshape(2, 4)
new_line

array([[ 0.,  2.,  4.,  6.],
       [ 8., 10., 12., 14.]])

### Combining Arrays

The most general command for combining arrays is `concatenate(arrs, d)`. It takes a list of arrays and concatenates them along axis $d$. Remember your 3-D array:

In [20]:
# Remember the `my2darr` 2-D numpy array
print(my2darr)
print(my2darr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [21]:
# Concatenate `my2darr` with itsef multiplied by 10 along dimension 0
conc_along0 = np.concatenate([my2darr, 10*my2darr], 0)
print(conc_along0)
print(conc_along0.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]
 [40 50 60]
 [70 80 90]]
(6, 3)


In [22]:
# Concatenate `my2darr` with itsef multiplied by 10 along dimension 1
conc_along1 = np.concatenate([my2darr, 10*my2darr], 1)
print(conc_along1)
print(conc_along1.shape)

[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]
 [ 7  8  9 70 80 90]]
(3, 6)


However, for common combinations there are special commands. We can use `vstack` to stack arrays in sequence vertically (row wise) or `hstack` to stack arrays in sequence horizontally (column wise).

In [23]:
# Stack `my2darr` vertically and horizontally
print(np.vstack([my2darr, 10 * my2darr]))
print('\n')
print(np.hstack([my2darr, 10 * my2darr]))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]
 [40 50 60]
 [70 80 90]]


[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]
 [ 7  8  9 70 80 90]]


### Operations

We can perform element-wise operations on arrays of any shape.

In [24]:
x_list = [1, 2, 3]

In [25]:
x = np.array([1, 2, 3])

print(x + 10)
print(3 * x)
print(1 / x)
print(x ** (-2 / 3))
print(2 ** x)

[11 12 13]
[3 6 9]
[1.         0.5        0.33333333]
[1.         0.62996052 0.48074986]
[2 4 8]


We can also operate between arrays, which must be of the same shape. If this is the case, they also do element-wise operations

In [26]:
y = np.arange(4, 7, 1)
print(x + y)     # [1+4, 2+5, 3+6]
print(x * y)     # [1*4, 2*5, 3*6]
print(x / y)     # [1/4, 2/5, 3/6]
print(x ** y)    # [1**4, 2**5, 3**6]

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


For doing vector or matrix multiplication, the command to be used is `dot`

In [27]:
print(x)
print(y)
x.dot(y)  # 1*4 + 2*5 + 3*6

[1 2 3]
[4 5 6]


32

With python 3.5 matrix multiplication got it's own operator

In [28]:
x @ y  # x.dot(y)

32

In [29]:
X = np.array([[i + j for i in range(3, 6)] for j in range(3)])
Y = np.diag([1, 1], 1) + np.diag([1], -2)

print(X)
print('\n')
print(Y)

[[3 4 5]
 [4 5 6]
 [5 6 7]]


[[0 1 0]
 [0 0 1]
 [1 0 0]]


The operator `*` returns the elements-wise multiplication of arrays with the same shape.

In [30]:
X * Y

array([[0, 4, 0],
       [0, 0, 6],
       [5, 0, 0]])

The operator `@` returns the matrix product of arrays with compatible shapes.

In [31]:
X @ Y

array([[5, 3, 4],
       [6, 4, 5],
       [7, 5, 6]])

**Exercise 2**: Take a 10x2 matrix representing $(x1,x2)$ coordinates and transform them into polar coordinates $(r,\theta)$.

*Hint 1: the inverse transformation is given by $x1 = r\cos\theta$, $x2 = r\sin\theta$*

*Hint 2: generate random numbers with the functions in numpy.random*

In [32]:
z = np.random.random((10, 2))
x1, x2 = z[:, 0], z[:, 1]
R = np.sqrt(x1 ** 2 + x2 ** 2)
T = np.arctan2(x2, x1)
print(R)
print(T)

[1.10725958 0.90629832 0.40956298 0.38194936 0.64503517 1.02683557
 0.89753381 1.02956203 0.34371282 0.97706481]
[0.50963416 0.32278992 0.27438299 0.30006334 1.41533726 0.40795643
 1.27878538 0.25391697 0.47221167 0.28332112]


#### Transposing

Transposition is a very important operation for linear algebra. Although NumPy is capable of correctly doing matrix-vector products regardless of the orientation of the vector, it is not the case for products of matrices.

In [33]:
Z = np.arange(0, 12, 1).reshape((4, 3))

In [34]:
print(Z)
print(y)
Z @ y

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[4 5 6]


array([ 17,  62, 107, 152])

In [35]:
print(Z)
print(y.T)
Z @ y.T

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[4 5 6]


array([ 17,  62, 107, 152])

In [36]:
print(Z)
print(X)
Z @ X  # (4 x 3) @ (3 x 3 cols) yields (4 x 3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[3 4 5]
 [4 5 6]
 [5 6 7]]


array([[ 14,  17,  20],
       [ 50,  62,  74],
       [ 86, 107, 128],
       [122, 152, 182]])

In [37]:
print(Z.T)
print(X)
Z.T @ X  # (3 x 4) @ (3 x 3) yields error

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[3 4 5]
 [4 5 6]
 [5 6 7]]


ValueError: ignored

#### Array Methods

NumPy provides some functions to make operations with the elements of our arrays, similar to the list functionalities. In fact, NumPy provides more functionalities than standard Python.

In [39]:
a = np.array([-4, -2, 1, 3, 5])
print(a.max())
print(a.min())
print(a.sum())
print(a.mean())
print(a.std())

5
-4
3
0.6
3.2619012860600183


Some interesting functions are `argmax` and `argmin`, which return the index of the maximum and minimum values in the array.

In [40]:
print(a.argmax())
print(a.argmin())

4
0


### Indexing/Slicing

We have already seen briefly that to access individual elements you use the bracket notation: `array[ax_0, ax_1, ...]`, where the `ax_i` denotes the coordinate in the `i`-th axis. Just like with lists, we can assign new values to existing elements.

In [41]:
r = [4, 5, 6, 7]
print(r[2])
# Reassigning the value stored in index 0
r[0] = 198
r

6


[198, 5, 6, 7]

We can slice within an index using `:`, just like we have seen in lists. A second `:` can be used to indicate the step size. `array[start:stop:stepsize]`. If we do not provide any `start` and `stop`, the selection will go from the very beginning until the end of the array.

In [42]:
s = np.arange(13)**2
print(s)

# Slice from 2 to 10
print(s[3:10])

# Starting by index 2, until index 10, take one every 3 elements 
print(s[2:10:3])

# Starting by index -5, until the end, pick every 2 elements
print(s[-5::2])

# Starting by index -5, until the end, pick every 2 elements backwards
print(s[-5::-2])

[  0   1   4   9  16  25  36  49  64  81 100 121 144]
[ 9 16 25 36 49 64 81]
[ 4 25 64]
[ 64 100 144]
[64 36 16  4  0]


The same applies to higher-dimensional arrays for every axis they have.

In [43]:
r = np.arange(36).reshape((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [44]:
# Pick rows 2 to 5, and cols 1 to 3 (remember, row 5 and col 3 not included)
r[2:5, 1:3]

array([[13, 14],
       [19, 20],
       [25, 26]])

We can select specific rows and columns, separated by commas

In [45]:
# Pick rows 1, 3 and 4, and cols 1 to 3 (remember, col 3 not included)
r[[1, 3, 4], 1:3]

array([[ 7,  8],
       [19, 20],
       [25, 26]])

A very useful tool is *boolean indexing*, where we apply a function, assignment... only to those elements of an array that satisfy some condition

In [46]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

**Exercise 3**: Create a random 1-dimensional array, and find which element is closest to 0.7

In [47]:
Z = np.random.uniform(0,1,100)
z = 0.7
m = Z[np.abs(Z - z).argmin()]
print(m)

0.6996295682321864


#### Copying Data

**Be very careful with copying and modifying arrays in NumPy!** Defining variables as parts of others will only provide a pointer to the allocated memory. Let us start with an example: let us define `r2` as a slice of `r`.

In [48]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

And now let's set all its elements to zero

In [49]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

If we now look at `r`, we see that it has also been changed!

In [50]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

The proper way of handling selections without modifying the original arrays is through the `copy` command.

In [51]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

Now we can safely modify `r_copy` without affecting `r`.

In [52]:
r_copy[:] = 10
print(f'{r_copy}\n')
print(f'{r}')

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


### Iterating Over Arrays

Finally, you can iterate over arrays in the same way as you iterate over lists

In [53]:
test = np.random.randint(0, 10, (4,3))
test

array([[9, 7, 6],
       [5, 3, 1],
       [1, 0, 9],
       [7, 2, 1]])

By default, we iterate over the first index which, for 2D arrays, corresponds to the rows.

In [54]:
for row in test:
    print(row)

[9 7 6]
[5 3 1]
[1 0 9]
[7 2 1]


Or by row index

In [55]:
for i in range(len(test)):
    print(test[i])

[9 7 6]
[5 3 1]
[1 0 9]
[7 2 1]


Or by row and index:

In [56]:
for i, row in enumerate(test):
    print(f'Row {i} is {row}')

Row 0 is [9 7 6]
Row 1 is [5 3 1]
Row 2 is [1 0 9]
Row 3 is [7 2 1]


In the same way as with lists, you can use `zip` to iterate over multiple iterables.

In [57]:
test2 = test**2
test2

array([[81, 49, 36],
       [25,  9,  1],
       [ 1,  0, 81],
       [49,  4,  1]])

In [58]:
for i, j in zip(test, test2):
    print(f'{i} + {j} = {i+j}')

[9 7 6] + [81 49 36] = [90 56 42]
[5 3 1] + [25  9  1] = [30 12  2]
[1 0 9] + [ 1  0 81] = [ 2  0 90]
[7 2 1] + [49  4  1] = [56  6  2]


**Exercise 4**: Create a function that iterates over the columns of a 2-dimensional array

In [59]:
def iterate(df):
    rows, cols = df.shape
    for i in range(cols):
        column = df[:, i]
        print(f'Column {i} is {column}')

iterate(test)

Column 0 is [9 5 1 7]
Column 1 is [7 3 0 2]
Column 2 is [6 1 9 1]


### Loading and Saving Data

To load and save data NumPy has the `loadtxt` and `savetxt` commands. However, they only work for two-dimensional arrays

In [62]:
np.savetxt('numpytest.txt', test)
np.loadtxt('numpytest.txt')

array([[9., 7., 6.],
       [5., 3., 1.],
       [1., 0., 9.],
       [7., 2., 1.]])